# Generated by Django 5.0.6 on 2024-06-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imgPost')),
            ],
        ),
    ]
