# Generated by Django 5.0.6 on 2024-06-19 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albonsapp', '0002_post_alter_postmodel_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imgPost')),
                ('date', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
    ]
